name: Unit Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run:  |
        sudo apt-get update
        sudo apt-get full-upgrade --assume-yes
        sudo apt install --assume-yes \
          build-essential
    - name: Generate Makefile
      run:  perl Makefile.PL
    - name: Run unit tests
      run:  make test

# vim: set ts=2 sw=2 et si:
